### ISSUE TITLE
Replace `case_insensitive` option with `case_sensitive` option

### ISSUE THREAD

**Issue by pocke** [sideci/goodcheck#4]
I think `case_insensitive: false` is not easy to understand. It has double negation, so I need to translate "not case_insensitive" to "case_sensitive".
So, I propose `case_sensitive` option instead. Both `case_sensitive: true` and `case_sensitive: false` are easy to understand.
What do you think?

**Comment by soutaro** [comment]
Fixed in https://github.com/sideci/goodcheck/releases/tag/v1.2.0 🎉
