### ISSUE TITLE
Support ruby 2.3.0 version~

### ISSUE THREAD

**Issue by sumyapp** [sideci/goodcheck#7]
Because my Mac default ruby version is `2.3.3p222`.
So non-ruby programmer require installing rbenv. It's a bother.
So if possible, please support 2.3.x version.

```
$ rbenv local system
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
```

**Comment by pocke** [comment]
I do not like this proposal. If goodcheck supports Ruby that is installed macOS by default, we cannot update required ruby version easily in the future. In other words, the required ruby version will be pinned 2.3 in long time.
I think we can provide a docker image of goodcheck. User just needs docker only, so I think it is easier.
